fixup remote_test.go TestRemote_GetWithErrorRemote() the test running server may have 80 port openned by default, which cause the test get wrong result
--- FAIL: TestRemote_GetWithErrorRemote (0.00s)
    remote_test.go:72:
        	Error Trace:	remote_test.go:72
        	Error:      	"bad status 404 Not Found for store.get" does not contain "remote call failed for store.get:"
        	Test:       	TestRemote_GetWithErrorRemote